name: Daily Scrape

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run scraper
        run: python scrape_narcotics.py

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Commit database
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data/narcotics.db
          git diff --staged --quiet || (git commit -m "Update narcotics db on $(date +'%Y-%m-%d')" && git push)

      - name: Check GitHub CLI Auth
        run: gh auth status
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create issue if DB changed
        run: |
          if git remote | grep origin; then
            git fetch origin
            git diff --quiet origin/main -- data/narcotics.db || \
            gh issue create \
              --title "⚠️ Narcotics list changed on $(date +'%Y-%m-%d')" \
              --body "The narcotics list has been updated and committed." \
              --repo "$GITHUB_REPOSITORY"
          else
            echo "No 'origin' remote found. Skipping issue creation."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

